name: Increment Visitor Counter

on:
  repository_dispatch:
    types: [increment_counter]

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Current Count
        id: read_count
        run: |
          COUNT=$(jq '.count' counter.json)
          echo "Current Count: $COUNT"
          echo "::set-output name=current::$COUNT"

      - name: Increment Count
        id: increment_count
        run: |
          NEW_COUNT=$(( ${{ steps.read_count.outputs.current }} + 1 ))
          jq --argjson new_count "$NEW_COUNT" '.count = $new_count' counter.json > tmp.json && mv tmp.json counter.json
          echo "New Count: $NEW_COUNT"

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Increment visitor counter"
          branch: main
